[build]
  command = "npm install -g pnpm && pnpm install && pnpm build"
  publish = "out/"
  # Use Ubuntu Focal 20.04 build image for stability
  image = "focal"

[build.environment]
  NODE_VERSION = "18"
  PNPM_HOME = "/opt/buildhome/.pnpm"
  PATH = "$PNPM_HOME/bin:$PATH"
  NPM_FLAGS = "--no-progress"

[functions]
  node_bundler = "esbuild"
